#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pcre
Version  : 8.38
Release  : 29
URL      : http://downloads.sourceforge.net/pcre/pcre-8.38.tar.gz
Source0  : http://downloads.sourceforge.net/pcre/pcre-8.38.tar.gz
Summary  : PCRE - Perl compatible regular expressions C library with 8 bit character support
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pcre-bin
Requires: pcre-lib
Requires: pcre-doc
BuildRequires : bzip2-dev
BuildRequires : pkgconfig(valgrind)
Patch1: cve-2016-1283.patch
Patch2: cve-2016-3191.patch

%description
-----------------------------------------------------------------
NOTE: This set of files relates to PCRE releases that use the original API,
with library names libpcre, libpcre16, and libpcre32. January 2015 saw the
first release of a new API, known as PCRE2, with release numbers starting at
10.00 and library names libpcre2-8, libpcre2-16, and libpcre2-32. The old
libraries (now called PCRE1) are still being maintained for bug fixes, but
there will be no new development. New projects are advised to use the new PCRE2
libraries.

%package bin
Summary: bin components for the pcre package.
Group: Binaries

%description bin
bin components for the pcre package.


%package dev
Summary: dev components for the pcre package.
Group: Development
Requires: pcre-lib
Requires: pcre-bin
Provides: pcre-devel

%description dev
dev components for the pcre package.


%package doc
Summary: doc components for the pcre package.
Group: Documentation

%description doc
doc components for the pcre package.


%package extras
Summary: extras components for the pcre package.
Group: Default

%description extras
extras components for the pcre package.


%package lib
Summary: lib components for the pcre package.
Group: Libraries

%description lib
lib components for the pcre package.


%prep
%setup -q -n pcre-8.38
%patch1 -p1
%patch2 -p1

%build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition -falign-functions=32 "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition -falign-functions=32 "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition -falign-functions=32 "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition -falign-functions=32 "
%configure --disable-static --enable-jit --enable-utf  --enable-unicode-properties --enable-pcre16 --enable-pcre32
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make check ; ./RunTest

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pcre-config
/usr/bin/pcregrep
/usr/bin/pcretest

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/pcre/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*

%files extras
%defattr(-,root,root,-)
/usr/lib64/libpcrecpp.so.0
/usr/lib64/libpcrecpp.so.0.0.1

%files lib
%defattr(-,root,root,-)
%exclude /usr/lib64/libpcrecpp.so.0
%exclude /usr/lib64/libpcrecpp.so.0.0.1
/usr/lib64/*.so.*
